GET http://localhost:3000/clients

###

GET http://localhost:3000/clients/647f0d8e7f458c267e0d92a0

###

POST http://localhost:8081/clients
Content-Type: application/json

{
    "first_name": "test2",
    "last_name": "Janeba",
    "age": 38,
    "phone_number": 111222333,
    "street": "Strasnice 5",
    "city": "Pardubice 53352"

}

###
DELETE http://localhost:3000/clients/646e1fd01c94cb9b4a0ee19b

###
PATCH http://localhost:3000/clients/646e1875a10f562c4dae1f90
Content-Type: application/json

{
    "firstname": "Jan"
}

###
GET http://localhost:3000/insurance

###

GET http://localhost:3000/insurance/

###

POST http://localhost:3000/insurance
Content-Type: application/json

{
    "name": "zivotni",
    "amount": 1000000
}

###
DELETE http://localhost:3000/insurance/6470d69b89fc29d101b2834b

###

PATCH http://localhost:3000/insurance/6470d7c0c17be2a28333d97c
Content-Type: application/json

{
    "name": "životní"
}

###

PATCH http://localhost:3000/clients/add_insurance/add/64899e88999f57c1af4a557f
Content-Type: application/json

{
    "insuranceEntry": {
    "type": "car",
    "amount": "10",
    "start_date": "1",
    "end_date": "2"
    }
}

###
DELETE http://localhost:3000/clients/649582d0dbd597adc8a0a7a1/insurance/del/64982076c2399c07508fb5e4
